# Generated by Django 4.1 on 2022-08-28 22:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=40)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000)),
            ],
            managers=[
                ('accounts', django.db.models.manager.Manager()),
            ],
        ),
    ]
