# Generated by Django 4.1 on 2022-08-29 13:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('Transactions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date_of_transaction',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_of_transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], default=0.045454545454545456, max_length=10),
            preserve_default=False,
        ),
    ]
